# Generated by Django 4.2.29 on 2026-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('course', models.CharField(choices=[('BSCS', 'BS Computer Science'), ('BSIT', 'BS Information Technology'), ('BSCE', 'BS Civil Engineering'), ('BSEE', 'BS Electrical Engineering'), ('BSME', 'BS Mechanical Engineering'), ('BSECE', 'BS Electronics Engineering'), ('BSED', 'BS Education'), ('BSBA', 'BS Business Administration'), ('BSNS', 'BS Nursing'), ('Other', 'Other')], max_length=100)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
