# Generated by Django 4.2.29 on 2026-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.CharField(default='PENDING', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='status_reason',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('school_transfer', 'School Transfer'), ('stopped_school', 'Stopped School'), ('other', 'Other')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSIT', 'BS Information Technology'), ('BSTM', 'BS Tourism Management'), ('BSHM', 'BS Hospitality Management'), ('BSED', 'BS Education'), ('BSCRIM', 'BS Criminology')], max_length=100),
        ),
    ]
